# Generated by Django 3.2.8 on 2022-07-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.TextField(null=True, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha',
            field=models.TextField(null=True, verbose_name='fecha'),
        ),
        migrations.AddField(
            model_name='libro',
            name='subtitulo',
            field=models.TextField(null=True, verbose_name='subtitulo'),
        ),
    ]
